Title: ZMA Charts
Airports:
  Bravo:
    - MIA
    - TPA
  Charlie:
    - FLL
    - PBI
    - RSW
  Delta:
    - APF
    - BCT
    - BOW
    - EQY
    - FPR
    - FXE
    - HST
    - LAL
    - MCF
    - NQX
    - OPF
    - PGD
    - PIE
    - PMP
    - RCO
    - SPG
    - SUA
    - TMB
    - VRB