Title: ZAU Charts
Airports:
  Bravo:
    - ORD
  Charlie:
    - CID
    - CMI
    - FWA
    - GRR
    - MDW
    - MKE
    - MLI
    - MSN
    - PIA
    - SBN
  Delta:
    - ALO
    - ARR
    - AZO
    - BMI
    - BTL
    - DBQ
    - DEC
    - DPA
    - EKM
    - ENW
    - GUS
    - GYY
    - JVL
    - LAF
    - LOT
    - MKG
    - MWC    
    - OSH
    - PWK
    - RFD
    - UES
    - UGN
    - VOK
