name: Build and Deploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
    #- name: Check date condition
      #run: |
      #  start_date="2023-10-05"
      #  current_date=$(date +"%Y-%m-%d")
      #  days_since_start=$(( ( $(date -d "$current_date" +%s) - $(date -d "$start_date" +%s) ) / 86400 ))
      #  if (( days_since_start % 28 != 0 )); then
      #   echo "Not the right day to run the job. Exiting early."
      #    exit 1
      #  fi
    # Your other steps go here
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/vzauartcc/charts:${{ github.sha }}
          ghcr.io/vzauartcc/charts:master
          ghcr.io/vzauartcc/charts:latest

  Deploy-to-Prod:
    needs: Build-and-Push  # This assumes you have a preceding job that builds and pushes the Docker image.
    runs-on: ubuntu-latest
    steps:
    - name: Initialize doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log into K8s cluster
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zau-k8s
    - name: Deploy F# app to cluster
      run: kubectl set image deployment/charts charts=ghcr.io/vzauartcc/charts:${{ github.sha }} --record -n zau-web-stack
    - name: Verify deployment
      run: kubectl rollout status deployment/charts -n zau-web-stack